apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanisha-insurance-deploy
  labels:
    app: tanisha-insurance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanisha-insurance-app
  template:
    metadata:
      labels:
        app: tanisha-insurance-app
    spec:
      containers:
      - name: tanisha-insurance-container
        image: agarwaltani/tanishainsuranceimage:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: tanisha-insurance-service
  labels:
    app: tanisha-insurance-app
spec:
  selector:
    app: tanisha-insurance-app

  type: NodePort
  ports:
  - nodePort: 30000
    port: 8083
    targetPort: 8083
    
